language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  #- sudo apt-get -y install nmap
# command to run tests
script:
  - pytest
